### ISSUE TITLE
Error getToken: ReferenceError: Can't find variable: Buffer

### ISSUE THREAD

**Issue by mathiastornblom** [noreajs/oauth-v2-client#1] opened 2022-01-03 04:13 UTC
in my callback.html I get an error that I traced back to 'basicAuthFunc.ts'
/**
 * Generate basic authentication header value
 * @param username username
 * @param password password
 */
export default function generateBasicAuthentication(
  username: string,
  password: string
) {
  return `Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`;
}

where it cant find Buffer

mycode:

import OauthClient from "oauth-v2-client";

const fortnoxapi = new OauthClient({
  oauthOptions: {
    clientId: "...",
    clientSecret: "...",
    callbackUrl: "https://localhost:3000/callback.html",
    accessTokenUrl: "https://apps.fortnox.se/oauth-v1/token",
    authUrl: "https://apps.fortnox.se/oauth-v1/auth",
    scopes: ["bookkeeping", "article", "companyinformation", "costcenter", "customer", "order"],
    state: "random",
    basicAuthHeader: true,
  },
  requestOptions: {
    bodyType: "x-www-form-urlencoded",
  },
});
var storage = window.localStorage;
var state = storage.getItem("state") || "";
console.log(state);
console.log(window.location.href);'fortnoxapi.authorizationCode.getToken({
  callbackUrl: window.location.href,
  state: state,
  onSuccess: (data) => {
    console.log(data);
  },
  onError: (error) => {
    console.log("Error getToken: " + error);
  },
});

**Comment by mathiastornblom** [comment] 2022-01-04 23:57
ReferenceError: Can't find variable: Buffer
generateBasicAuthentication — basicAuthFunc.js:9
(anonym funktion) — AuthorizationCodeGrantControl.js:153
step — AuthorizationCodeGrantControl.js:46
(anonym funktion) — AuthorizationCodeGrantControl.js:21
Promise
(anonym funktion) — AuthorizationCodeGrantControl.js:17
./src/callback/callback.ts — callback.ts:22
__webpack_require__ — bootstrap:24
(anonym funktion) — startup:6
Global kod — startup:6

**Comment by lambou** [comment] 2023-10-22 18:15
Hi @mathiastornblom and sorry for the late reply. 

The Buffer variable is not defined outside of a node environment. The problem is now fixed in the latest version (v1.2.3)

**Closed as completed** 2023-10-22 18:15 UTC
